### ISSUE TITLE
Approach - "X" to close overlay is unclickable

### ISSUE THREAD

**Issue by theastralj** [BraveUX/website#145]

**Comment by callmecavs** [comment]
added a z-index to this, can you test it again @theastralj?

fixed the positioning
* it should be 7.5% from right on homepage
* it should be 15px from right on interior pages

**Comment by theastralj** [comment]
It's still appearing in PC Chrome and Firefox. Basically what happens is, when you click on the "X", it highlights the "Fold, sh-mold" text

![image](https://cloud.githubusercontent.com/assets/1764989/5617864/385276f2-94e1-11e4-8fc9-1e883093516f.png)
